AllCops:
    NewCops: enable
Layout/LineLength:
    Max : 150
Metrics/AbcSize:
    Enabled : true
Metrics/BlockLength:
    Enabled : true
    Exclude:
        - 'spec/**/*'
Metrics/BlockNesting:
    Enabled : true
Metrics/ClassLength:
    Enabled : true
Metrics/CyclomaticComplexity:
    Enabled : true
Metrics/MethodLength:
    Enabled : true
Metrics/ModuleLength:
    Enabled : true
Metrics/ParameterLists:
    Enabled : true
Metrics/PerceivedComplexity:
    Enabled : true
