AllCops:
    NewCops: enable

Gemspec/RequireMFA:
    Enabled: false

Layout/LineLength:
    Max : 150

Style/NumericLiterals:
    Enabled : false

Metrics/BlockLength:
    Exclude:
        - 'spec/**/*'
