AllCops:
    NewCops: enable

Layout/MultilineMethodCallIndentation:
    EnforcedStyle: aligned
Layout/LineLength:
    Max : 150

Metrics/ClassLength:
    Enabled : true
Metrics/AbcSize:
    Enabled : true
Metrics/BlockLength:
    Exclude:
        - 'spec/**/*'

Style/PercentLiteralDelimiters:
    PreferredDelimiters:
        "%i": "[]"
        "%I": "[]"
        "%r": "{}"
        "%w": "[]"
        "%W": "[]"
Style/StringLiterals:
    EnforcedStyle: double_quotes
Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: no_comma
Style/TrailingCommaInArrayLiteral:
    EnforcedStyleForMultiline: no_comma
Style/TrailingCommaInHashLiteral:
    EnforcedStyleForMultiline: no_comma


